In [1]:
import numpy as np

In [30]:
a=np.random.randint(30,99,(8,9))

In [31]:
a

array([[78, 40, 90, 89, 89, 74, 82, 51, 92],
       [82, 88, 91, 63, 75, 54, 48, 85, 57],
       [92, 48, 92, 86, 72, 97, 88, 37, 48],
       [95, 49, 49, 32, 62, 65, 63, 89, 51],
       [50, 33, 37, 50, 43, 46, 70, 44, 59],
       [30, 78, 72, 77, 34, 36, 55, 67, 79],
       [53, 35, 73, 68, 80, 68, 75, 62, 86],
       [47, 48, 71, 63, 31, 73, 40, 80, 43]])

In [32]:
a[1:5,1:6]

array([[88, 91, 63, 75, 54],
       [48, 92, 86, 72, 97],
       [49, 49, 32, 62, 65],
       [33, 37, 50, 43, 46]])

In [36]:
a.shape

(8, 9)

In [35]:
a.ndim

2

In [34]:
a[2]

array([92, 48, 92, 86, 72, 97, 88, 37, 48])

In [37]:
a[1:9]

array([[82, 88, 91, 63, 75, 54, 48, 85, 57],
       [92, 48, 92, 86, 72, 97, 88, 37, 48],
       [95, 49, 49, 32, 62, 65, 63, 89, 51],
       [50, 33, 37, 50, 43, 46, 70, 44, 59],
       [30, 78, 72, 77, 34, 36, 55, 67, 79],
       [53, 35, 73, 68, 80, 68, 75, 62, 86],
       [47, 48, 71, 63, 31, 73, 40, 80, 43]])

In [38]:
#array[row_start: row_end : row_step , col_start: col_end:col_step]

In [39]:
import pandas as pd

In [40]:
pd.Series()

Series([], dtype: object)

In [44]:
k=([4,7],[2,9],[7,3],[90,50])
k

([4, 7], [2, 9], [7, 3], [90, 50])

In [45]:
np.array(k)

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [49]:
t=pd.Series(k)
t

0      [4, 7]
1      [2, 9]
2      [7, 3]
3    [90, 50]
dtype: object

In [54]:
pd.DataFrame(t)

0
0    [4, 7]
1    [2, 9]
2    [7, 3]
3  [90, 50]